dist: trusty
sudo: required
language: bash

before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash

notifications:
  slack:
    rooms:
      secure: oHmTtlayhbqaVJuaUoewLFJXlN6/njUGzyNq2wE2MbOYfOll6LnjUgdji/KEPOdJvKswA2sidZCzYjJFU6KbDaTXY0u4q5wSrLPtBsCMcNaHLBK6K7IdC8udYt6HK7J1OWpr7AxBlbaJnQ30tGRRoETy1qISy96G6XqjdFmNwKrR0MrRzyejLoQN8I0B03lATniMNN8YehEZNbAkDU6/o7R1o/KSg3duXfL7EMjvGfRIQTQteYHj+xIzYD4yjM8QAuk5XdnC0fk1Hn3gdbQjqRWzoNyGRSWbk7WvKhgUBr7VHUE3coCM553sRhVs4XR2gqORDEsa/E5RfeGfab+ew4xrHBfGHnZGG/0n2b6ticfsl3gC7Wpz1n8x7Grt6aXmsMcZVp/wU3IvoZZuUY5bTEf768+R7QoD4p2aR9rNqP9H0Ntk06hnjyHXEVFvJGvOZCUowFMyxtTMHtTM4IRrRhbrgO1skG1knMSzfmrsu4tjjMYKVFUsPbrVFrGdBdifhHMZno1D35WEyv3wmcFLrIYGxHrj/MiNkqiHq2TSofLrJSrOhJrgj4YLwd/n2yeSESjLWcJw+oXervb0/GthfOVGswPgQPGe4H+AdAMCjESzrigJJQ3w0JAmYiLcgcDSGbG3fUGqgWeBh2GfpFRnLG8LvXIdt2VS3aJfeYT3p2E=
